select 
    ORDER_ID ,
	CUSTOMER_ID ,
	ORDER_STATUS,
	try_to_timestamp(ORDER_PURCHASE_TIMESTAMP) ORDER_PURCHASE_TIMESTAMP,
	try_to_timestamp(ORDER_APPROVED_AT) ORDER_APPROVED_AT,
	try_to_timestamp(ORDER_DELIVERED_CARRIER_DATE) ORDER_DELIVERED_CARRIER_DATE,
	try_to_timestamp(ORDER_DELIVERED_CUSTOMER_DATE) ORDER_DELIVERED_CUSTOMER_DATE,
	try_to_timestamp(ORDER_ESTIMATED_DELIVERY_DATE) ORDER_ESTIMATED_DELIVERY_DATE
    from {{source('raw_source', 'ORDERS' )}}